version: '3.8'

services:
  numa_api:
    build:
      context: ./services/numa-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./services/numa-api/.env
    depends_on:
      - mcp_server
    networks:
      - numa_network

  mcp_server:
    build:
      context: ./services/mcp-server
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file:
      - ./services/mcp-server/.env
    depends_on:
      - model_server
    networks:
      - numa_network

  model_server:
    build:
      context: ./services/model-server
      dockerfile: Dockerfile
    ports:
      - "11434:11434" # Puerto est√°ndar de Ollama
    volumes:
      - ollama_models:/root/.ollama
    networks:
      - numa_network

networks:
  numa_network:
    driver: bridge

volumes:
  ollama_models: